"""Turn measured results into things a report or a viva can use.

Two artefacts, both generated from the same files every other surface reads, so
a number in a slide and a number in the terminal cannot drift apart:

  LaTeX      booktabs tables and Beamer frames written from `figures/*.csv`.
              Retyping a table into a report is where transcription errors get
              in, and this project's results have moved four times this month.
  Proof      the raw prompt beside the compressed one, every removed sentence
              struck through AND labelled, as a static page a reviewer can read
              end to end and check the logic survived the pruning.

Neither invents a figure. If a CSV is missing the section is omitted with a
note saying which command regenerates it.
"""

from __future__ import annotations

import csv
import html as html_mod
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]

#: Chrome is the PDF engine already used by tools/make_pdf.py: real CSS paged
#: media, and nothing new to install.
CHROME_CANDIDATES = (
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
)


def find_chrome() -> str | None:
    for path in CHROME_CANDIDATES:
        if Path(path).exists():
            return path
    return shutil.which("chrome") or shutil.which("msedge")


# ------------------------------------------------------------------ LaTeX --


def tex_escape(text: str) -> str:
    out = str(text)
    for old, new in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                     ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                     ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
                     ("→", r"$\rightarrow$"), ("×", r"$\times$"), ("−", "-"), ("–", "--")):
        out = out.replace(old, new)
    return out


def _rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def tabular(rows: list[dict[str, str]], columns: list[str], *, caption: str, label: str,
            align: str | None = None, bold_first: bool = True) -> str:
    """A booktabs table: rule above, under the header, at the foot, none vertical."""
    if not rows:
        return ""
    align = align or ("l" + "r" * (len(columns) - 1))
    head = " & ".join(rf"\textbf{{{tex_escape(c)}}}" for c in columns)
    body = []
    for row in rows:
        cells = [tex_escape(row.get(c, "")) for c in columns]
        if bold_first:
            cells[0] = rf"\texttt{{{cells[0]}}}"
        body.append(" & ".join(cells) + r" \\")
    return "\n".join([
        r"\begin{table}[htbp]", r"  \centering", rf"  \caption{{{tex_escape(caption)}}}",
        rf"  \label{{tab:{label}}}", rf"  \begin{{tabular}}{{{align}}}", r"    \toprule",
        f"    {head} \\\\", r"    \midrule",
        *(f"    {line}" for line in body),
        r"    \bottomrule", r"  \end{tabular}", r"\end{table}", "",
    ])


@dataclass(frozen=True, slots=True)
class Artefact:
    path: Path
    what: str
    lines: int


def latex_tables(figures: Path, out: Path) -> Artefact:
    """Every committed result table, as LaTeX, from the CSVs that hold them."""
    parts: list[str] = [
        "% Generated by `parsimony export --latex`. Do not edit by hand:",
        "% every number here is read from figures/*.csv, which reproduce.py writes.",
        r"% Requires \usepackage{booktabs} in the preamble.",
        "",
    ]
    missing: list[str] = []

    def section(name: str, csv_name: str, columns: list[str], caption: str,
                label: str, limit: int | None = None) -> None:
        path = figures / csv_name
        if not path.exists():
            missing.append(csv_name)
            return
        rows = _rows(path)
        if limit:
            rows = rows[:limit]
        parts.append(f"% ---- {name} " + "-" * max(0, 60 - len(name)))
        parts.append(tabular(rows, [c for c in columns if c in rows[0]],
                             caption=caption, label=label))

    section("factorial ablation", "ablation.csv",
            ["cell", "input", "input red %", "output", "output red %", "reduction %",
             "cache hits", "middleware ms"],
            "Factorial ablation over M1, M2, M3 and M5: tokens and reductions per cell.",
            "ablation")
    section("main effects", "effects.csv",
            ["effect", "order", "estimate (pp)", "partial eta squared"],
            "Main effects and interactions, in percentage points of total token reduction.",
            "effects", limit=8)
    section("long context", "longctx_real.csv",
            ["method", "correct", "accuracy %", "95% CI", "context kept %", "prompt tokens",
             "prefill ms", "McNemar p"],
            "Long-context question answering on the held-out split, real model.",
            "longctx")
    section("confirmation split", "longctx_confirm.csv",
            ["method", "correct", "accuracy %", "context kept %", "prompt tokens", "prefill ms"],
            "Confirmation on the split authored after the first run and never tuned against.",
            "longctxconfirm")
    section("conversations", "followups.csv",
            ["method", "correct", "accuracy %", "fact kept", "prompt tokens", "prefill ms",
             "McNemar p"],
            "History management: does the fact the last question needs survive?",
            "followups")
    section("encoders", "encoders.csv",
            ["encoder", "design", "false answers", "false %", "true hits", "true %",
             "ms per question"],
            "Cache safety and reuse under two encoders and two verification policies.",
            "encoders")
    section("off-topic", "longctx_offtopic.csv", ["method", "questions", "context kept %"],
            "Questions the documents cannot answer: how much context each method still sends.",
            "offtopic")

    if missing:
        parts.append("% Omitted, no data file: " + ", ".join(missing))
        parts.append("% Regenerate with: python reproduce.py --out figures")
    text = "\n".join(parts) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return Artefact(out, "booktabs tables", text.count("\n"))


def beamer_slides(figures: Path, out: Path, *, title: str = "Parsimony",
                  subtitle: str = "Token-efficient LLM interaction on CPU-only hardware",
                  authors: str = "Arrsh Tripathi \\and Alok Singh \\and Dev Singh") -> Artefact:
    """A self-contained Beamer deck of the results, ready to compile."""
    def table_or_note(csv_name: str, columns: list[str], caption: str, label: str,
                      limit: int | None = None) -> str:
        path = figures / csv_name
        if not path.exists():
            return rf"\textit{{No {tex_escape(csv_name)}; run \texttt{{reproduce.py}}.}}"
        rows = _rows(path)
        if limit:
            rows = rows[:limit]
        cols = [c for c in columns if c in rows[0]]
        head = " & ".join(rf"\textbf{{{tex_escape(c)}}}" for c in cols)
        body = "\n".join("      " + " & ".join(tex_escape(r.get(c, "")) for c in cols) + r" \\"
                         for r in rows)
        return "\n".join([
            r"  \begin{center}", rf"  \begin{{tabular}}{{l{'r' * (len(cols) - 1)}}}",
            r"    \toprule", f"    {head} \\\\", r"    \midrule", body,
            r"    \bottomrule", r"  \end{tabular}", r"  \end{center}",
        ])

    frames = [
        (r"What it is",
         r"""  \begin{itemize}
    \item Middleware between an application and a small language model on CPU.
    \item Seven modules propose edits; one gate refuses any that would change meaning.
    \item Every figure below regenerates from raw logs in about two minutes.
  \end{itemize}"""),
        (r"Savings do not compound",
         table_or_note("effects.csv", ["effect", "estimate (pp)", "partial eta squared"],
                       "Main effects", "effects", limit=6)),
        (r"Long context: a fifth of the prompt, same answers",
         table_or_note("longctx_real.csv",
                       ["method", "correct", "context kept %", "prompt tokens", "prefill ms"],
                       "Long context", "longctx")),
        (r"Conversations: recency answers none of them",
         table_or_note("followups.csv",
                       ["method", "correct", "fact kept", "prompt tokens", "prefill ms"],
                       "Follow-ups", "followups")),
        (r"A better encoder broke the safety design",
         table_or_note("encoders.csv",
                       ["encoder", "design", "false answers", "true hits", "ms per question"],
                       "Encoders", "encoders")),
    ]
    body = "\n\n".join(
        "\n".join([rf"\begin{{frame}}{{{title_}}}", content, r"\end{frame}"])
        for title_, content in frames)
    text = "\n".join([
        "% Generated by `parsimony export --latex`. Every number is read from figures/*.csv.",
        r"\documentclass[aspectratio=169]{beamer}",
        r"\usepackage{booktabs}",
        r"\usetheme{metropolis}" + "  % falls back to default if metropolis is absent",
        rf"\title{{{title}}}", rf"\subtitle{{{subtitle}}}", rf"\author{{{authors}}}",
        r"\date{\today}", "", r"\begin{document}", r"\maketitle", "", body, "",
        r"\end{document}", "",
    ])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return Artefact(out, "Beamer deck", text.count("\n"))


# ------------------------------------------------------------------ proof --

PROOF_CSS = """
  :root { color-scheme: light; }
  body { font-family: Cambria, Constantia, Georgia, serif; margin: 0; color: #111; }
  main { max-width: 190mm; margin: 0 auto; padding: 14mm 0; }
  h1 { font-size: 20pt; margin: 0 0 2mm; }
  .sub { color: #555; font-size: 10pt; margin-bottom: 8mm; }
  .stats { display: flex; gap: 8mm; margin: 0 0 8mm; font-size: 10pt; }
  .stat b { display: block; font-size: 16pt; font-variant-numeric: tabular-nums; }
  .cols { display: grid; grid-template-columns: 1fr 1fr; gap: 6mm; }
  section { break-inside: avoid; }
  h2 { font-size: 11pt; text-transform: uppercase; letter-spacing: .06em; color: #444;
       border-bottom: 1px solid #ccc; padding-bottom: 1mm; }
  .doc { font-size: 9.5pt; line-height: 1.45; }
  .doc h3 { font-size: 9.5pt; margin: 4mm 0 1mm; color: #333; }
  .kept { color: #111; }
  .gone { color: #999; text-decoration: line-through; }
  .tag { font-family: Consolas, monospace; font-size: 7.5pt; color: #b00;
         text-decoration: none; white-space: nowrap; }
  .keep-tag { color: #070; }
  .note { font-size: 8.5pt; color: #555; margin-top: 6mm; }
  @page { size: A4; margin: 16mm 14mm; }
"""


def proof_html(question: str, audit, *, answer: str = "", model: str = "",
               title: str = "Prompt verification") -> str:
    """Raw against compressed, with every removal labelled as well as struck.

    Strike-through is a rendering; a reviewer reading a printout needs the
    label, and an auditor needs the reason. Both are here, beside the sentence
    they belong to.
    """
    kept_html: list[str] = []
    raw_html: list[str] = []
    current = None
    for unit in audit.units:
        if unit.source_label != current:
            current = unit.source_label
            raw_html.append(f"<h3>{html_mod.escape(current)}</h3>")
            kept_html.append(f"<h3>{html_mod.escape(current)}</h3>")
        text = html_mod.escape(unit.text)
        if unit.kept:
            raw_html.append(f'<span class="kept">{text}</span> ')
            kept_html.append(f'<span class="kept">{text}</span> ')
        else:
            raw_html.append(
                f'<span class="gone">{text}</span> '
                f'<span class="tag">[removed: {html_mod.escape(unit.tag.lower())} — '
                f'{html_mod.escape(unit.detail)}]</span> ')
    stats = [
        ("tokens sent", f"{audit.tokens_after:,}"),
        ("tokens written", f"{audit.tokens_before:,}"),
        ("removed", f"{audit.removed_pct:.0f}%"),
        ("sentences kept", f"{sum(1 for u in audit.units if u.kept)}/{len(audit.units)}"),
    ]
    stat_html = "".join(
        f'<div class="stat">{html_mod.escape(label)}<b>{html_mod.escape(value)}</b></div>'
        for label, value in stats)
    answer_html = (f'<p class="note"><b>Answer returned:</b> {html_mod.escape(answer)}</p>'
                   if answer else "")
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{html_mod.escape(title)}</title>
<style>{PROOF_CSS}</style></head><body><main>
<h1>{html_mod.escape(title)}</h1>
<p class="sub">Question: <b>{html_mod.escape(question)}</b>
{(" · model: " + html_mod.escape(model)) if model else ""}
 · stopped by {html_mod.escape(audit.stopped_by)}</p>
<div class="stats">{stat_html}</div>
<div class="cols">
  <section><h2>As written, with removals marked</h2>
    <div class="doc">{"".join(raw_html)}</div></section>
  <section><h2>As sent to the model</h2>
    <div class="doc">{"".join(kept_html)}</div></section>
</div>
{answer_html}
<p class="note">Every removal is labelled with the decision that produced it:
<b>floor</b> — below the relevance floor; <b>redundant</b> — overlaps a kept sentence;
<b>budget</b> — relevant, but the token budget was spent; <b>off-topic</b> — the question
shares almost no vocabulary with this context. Kept sentences are verbatim and in their
original order, which the fidelity gate checks independently of this page.</p>
</main></body></html>"""


def write_proof(html_text: str, out: Path) -> Artefact:
    """Write the proof as HTML, and as PDF when a browser engine is available."""
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.suffix.lower() != ".pdf":
        out.write_text(html_text, encoding="utf-8")
        return Artefact(out, "proof page (HTML)", html_text.count("\n"))

    chrome = find_chrome()
    if chrome is None:
        fallback = out.with_suffix(".html")
        fallback.write_text(html_text, encoding="utf-8")
        return Artefact(fallback, "proof page (HTML; no browser engine found for PDF)",
                        html_text.count("\n"))
    tmp = Path(tempfile.gettempdir()) / f"parsimony_proof_{out.stem}.html"
    tmp.write_text(html_text, encoding="utf-8")
    subprocess.run(
        [chrome, "--headless", "--disable-gpu", "--no-pdf-header-footer",
         "--virtual-time-budget=5000", f"--print-to-pdf={out.resolve()}",
         tmp.resolve().as_uri()],
        check=True, capture_output=True, timeout=180)
    return Artefact(out, "proof document (PDF)", 0)
